### PR TITLE
Update DiscordFreeEmojis.plugin.js

### PR DESCRIPTION
**Pull request by thc282**
add css style 
more detail is inside [#13](https://github.com/EpicGazel/DiscordFreeEmojis/issues/13#issuecomment-2295122206) issues

### CODE REVIEW

**Comment by Bergbok** [comment]
In my opinion the CSS should be kept in [Useful.css](https://github.com/EpicGazel/DiscordFreeEmojis/blob/master/Useful.css) so that users can easily disable/modify the rules to their liking.

**Comment by thc282** [comment]
true. but i didnt touch discord plugin before
i saw others is just write inside the plugin.js. instead of extra css

in most of plugin. only 2-3 is reading outside css folder

**Comment by EpicGazel** [comment]
It would be ideal to add a toggle for built-in CSS settings. Not everyone wants giant emojis for example.

**Comment by thc282** [comment]
> It would be ideal to add a toggle for built-in CSS settings. Not everyone wants giant emojis for example. I'll probably get to it eventually if you don't.

sry for Mislead. the giant emoji is another plugin

**Pull request merged**
